require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - db/**/*
    - bin/**/*
    - log/**/*
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*

### Rails

Rails:
  Enabled: true

Rails/FilePath:
  EnforcedStyle: arguments

### Bundler

Bundler/OrderedGems:
  Enabled: false

### Metrics

Metrics/AbcSize:
  Max: 35

Metrics/ClassLength:
  Max: 110

Metrics/BlockLength:
  Max: 150

Metrics/MethodLength:
  Max: 30

### Style

Style/BlockComments:
  Exclude:
    - "spec/spec_helper.rb"

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/LambdaCall:
  Enabled: false

### Layout

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/LineLength:
  Max: 165
